name: 'Get tag name'
description: 'Gets current tag name and puts it into an environment variable GIT_TAG_NAME.'
author: 'Oleg Tarasov'
runs:
  using: 'node12'
  main: 'lib/main.js'
inputs:
  tagRegex:
    description: 'Regex to tag against match'
    required: false
  tagRegexGroup: 
    description: 'Regex group to capture'
    required: false
    default: 1
outputs:
  tag:
    description: The tag name.
branding:
  icon: 'tag'
  color: 'orange'
